#  Run in production with
#  $ docker-compose -f docker-compose.yml -f docker-compose-production.yml up -d

version: '3.6'
services:
  app:
    build: ./
    container_name: erd-app
    working_dir: /usr/src/app
    depends_on:
      - postgres
      - hasura
    ports:
      - '9696:3000'
    environment:
      HOST: 0.0.0.0
      NUXT_XENON_API_KEY: 'Your Xenon-server api key here'

  upload_server:
    build: ./upload-server
    container_name: erd-upload-server
    command: yarn start
    volumes:
      - ./upload-server:/usr/src/app/cwl_files
    working_dir: /usr/src/app
    ports:
      - "7000:7000"
