version: '3.6'
services:
  postgres:
    container_name: erd-postgres
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PRODUCTION_POSTGRES_PASSWORD:-postgrespassword}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      default:
        ipv4_address: 172.26.0.10

  hasura:
    container_name: erd-hasura
    image: hasura/graphql-engine:v1.3.3.cli-migrations-v2
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${PRODUCTION_POSTGRES_USER:-postgres}:${PRODUCTION_POSTGRES_PASSWORD:-postgrespassword}@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
      HASURA_GRAPHQL_ADMIN_SECRET: ${PRODUCTION_HASURA_GRAPHQL_ADMIN_SECRET:-adminpassword}
    volumes:
      - "./hasura/migrations:/hasura-migrations"
      - "./hasura/metadata:/hasura-metadata"

volumes:
  db_data:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16
